#baseURL = 'https://plabordab.github.io/portfolio_hugo'
baseURL = 'http://localhost'
languageCode = 'es'
title = 'Pilar Laborda'
theme = ['universal']

defaultContentLanguage = 'es'

# Sistema de comentarios desactivados
disqusShortname = ""

# Menú

[menu]

[[menu.main]]
    name       = "Manuales"
    identifier = "menu.manuales"
    weight     = 1

    [[menu.main]]
        name       = "Hugo"
        identifier = "section.hugo"
        url        = ""
        weight     = 1
        parent     = "menu.manuales"
        post       = 1


            [[menu.main]]
                name       = "Instalación Hugo"
                url        = "/hugo_instal/"
                weight     = 1
                parent     = "section.hugo"

            [[menu.main]]
                name       = "Configuración Hugo"
                url        = "/hugo_config/"
                weight     = 2
                parent     = "section.hugo"

            [[menu.main]]
                name       = "Tema Universal"
                url        = "/hugo_tema/"
                weight     = 3
                parent     = "section.hugo"

            [[menu.main]]
                name       = "Markdown"
                url        = "/hugo_md/"
                weight     = 4
                parent     = "section.hugo"



    [[menu.main]]
        name       = "Git"
        identifier = "section.git"
        url        = ""
        weight     = 2
        parent     = "menu.manuales"
        post       = 2


            [[menu.main]]
                name       = "Git Init"
                url        = "/git_init/"
                weight     = 1
                parent     = "section.git"

            [[menu.main]]
                name       = "Git Push"
                url        = "/git_push/"
                weight     = 2
                parent     = "section.git"

            [[menu.main]]
                name       = "Git Pull"
                url        = "/git_pull/"
                weight     = 3
                parent     = "section.git"

    [[menu.main]]
        name       = "Docker"
        identifier = "section.docker"
        url        = ""
        weight     = 3
        parent     = "menu.manuales"
        post       = 3

            [[menu.main]]
                name       = "Instalación Docker"
                url        = "/docker_instal/"
                weight     = 1
                parent     = "section.docker"

            [[menu.main]]
                name       = "Configuración Docker"
                url        = "/docker_config/"
                weight     = 2
                parent     = "section.docker"

            [[menu.main]]
                name       = "Apache"
                url        = "/docker_apache/"
                weight     = 3
                parent     = "section.docker"


[[menu.main]]
    identifier = "contact"
    name       = "Sobre mí"
    url        = "/contact/"
    weight     = 2


# Menú de enlaces sociales de la barra superior


[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/plabordab"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Linkedin"
    url = "https://www.linkedin.com/in/pilar-laborda-berd%C3%BAn-13568060"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"


[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:pilarlabordaweb@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"


[params]

    style = 'default'
    dropdown_mouse_over = false
    disabled_logo = false
    logo_text = "Pilar Laborda"
    logo = "img/template-LOGO.png"

    # Habilitar el formulario de contacto

       email = "pilarlabordaweb@gmail.com"
       formspree_action = "https://formspree.io/f/maykdkdz"
       contact_form_ajax = false
    
    # Habilitar captcha en el formulario 

    # Deshabilito esta opción ya que el captcha no me permite el dominio: 'https://plabordab.github.io/portfolio_hugo'

        enableRecaptchaInContactForm = false
    #    googleRecaptchaKey = "6Lcb15siAAAAAA5fmS0ICspqfEZ53rHyjiodUI5Z"

    
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Pilar Laborda</strong>
        <br>Zaragoza
        <br>
        <strong>SPAIN</strong>
      </p>
      """

# Barra superior con iconos sociales 

[params.topbar]
    enable = true
   

# Widgets para la barra lateral derecha

[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselHomepage]

    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000
      

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

# Widgets de características


[params.features]
    enable = true
    cols = 2 # Default: 2, Available values 2,3,4,6



# Idiomas

# Este tema carece de esta funcionalidad

[languages]
  [languages.es]
    contentDir = 'content/es'
    languageName = 'Español'
    weight = 10
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 20
  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'Français'
    weight = 30



# Gráficos

[params.mermaid]
    enable = true

[params.see_more]

   enable = true
   icon = "fas fa-user"
   title = "Es momento de descansar"
   subtitle = "Disfruta con nuestra oferta televisiva"
   link_url = "/ocio_tv/"
   link_text = "Descúbrela"
